# Generated by Django 5.1.1 on 2024-09-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_iron_sheets", models.IntegerField(default=1000)),
                ("total_cement_packs", models.IntegerField(default=500)),
                ("remaining_iron_sheets", models.IntegerField()),
                ("remaining_cement_packs", models.IntegerField()),
            ],
        ),
    ]
