# Generated by Django 5.1.1 on 2024-10-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_schoolstock_alter_stock_served_schools"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="served_schools",
        ),
    ]
