# Generated by Django 5.1.1 on 2024-10-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_stock_served_schools"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="served_schools",
            field=models.ManyToManyField(
                related_name="served_schools",
                through="api.SchoolStock",
                to="api.school",
            ),
        ),
    ]
